---
- name: Create the pulp.pulpproject.org/v1alpha1.Pulp
  k8s:
    state: present
    namespace: '{{ namespace }}'
    definition: "{{ lookup('template', '/'.join([samples_dir, cr_file])) | from_yaml }}"
    wait: yes
    wait_timeout: 300
    wait_condition:
      type: Running
      reason: Successful
      status: "True"
  vars:
    cr_file: 'pulp_v1alpha1_pulp.travis.yaml'

- name: Add assertions here
  assert:
    that: true
    fail_msg: FIXME Add real assertions for your operator
