apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: automationhubs.hub.ansible.com
spec:
  group: hub.ansible.com
  names:
    kind: AutomationHub
    listKind: AutomationHubList
    plural: automationhubs
    singular: automationhub
  scope: Namespaced
  versions:
  - name: v1beta1
    served: true
    storage: true
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        description: Schema validation for the Pulp CRD
        properties:
          spec:
            properties:
              deployment_type:
                description: Name of the deployment type
                type: string
              registry:
                description: The container image registry to use for pulling images.
                type: string
                default: quay.io
              project:
                description: The container image registry project for pulling images.
                type: string
                default: pulp
              image:
                description: The image name (repo name) for the pulp image.
                type: string
                default: pulp
              image_web:
                description: The image name (repo name) for the pulp webserver image.
                type: string
                default: pulp-web
              tag:
                description: The image tag for the pulp image.
                type: string
                default: stable
              pulp_settings:
                description: The pulp settings.
                properties:
                  debug:
                    type: string
                type: object
              pulp_admin_password_secret:
                  description: Secret where the administrator password can be found
                  type: string
              postgres_configuration_secret:
                  description: Secret where the database configuration can be found
                  type: string
              postgres_initdb_args:
                  description: The arguments to be passed to initialize the database
                  type: string
              postgres_host_auth_method:
                  description: The method to be used for database host authentication
                  type: string
              postgres_image:
                description: Registry path to the PostgreSQL container to use
                type: string
              postgres_resource_requirements:
                description: Resource requirements for the PostgreSQL container
                properties:
                  requests:
                    properties:
                      cpu:
                        type: string
                      memory:
                        type: string
                      storage:
                        type: string
                    type: object
                  limits:
                    properties:
                      cpu:
                        type: string
                      memory:
                        type: string
                      storage:
                        type: string
                    type: object
                type: object
              postgres_storage_class:
                description: Storage class to use for the PostgreSQL PVC
                type: string
              postgres_data_path:
                description: Path where the PostgreSQL data are located
                type: string
              pulp_storage_type:
                description: Configuration for the storage type to be utilized
                type: string
                default: File
                enum:
                  - file
                  - File
                  - s3
                  - S3
                  - azure
                  - Azure
              pulp_file_storage:
                description: Configuration for the persistentVolumeClaim for /var/lib/pulp.
                properties:
                  access_mode:
                    description: The file storage access mode.
                    type: string
                    default: ReadWriteOnce
                    enum:
                      - ReadWriteMany
                      - ReadWriteOnce
                  size:
                    description: The size of the file storage; for example 100Gi.
                    type: string
                    default: 2Gi
                type: object
              pulp_object_storage_s3_secret:
                description: The secret for S3 compliant object storage configuration.
                type: string
              pulp_object_storage_azure_secret:
                description: The secret for Azure blob storage configuration.
                type: string
              pulp_hostname:
                description: The hostname of the instance
                type: string
              ingress_type:
                description: The ingress type to use to reach the deployed instance
                type: string
                enum:
                  - none
                  - Ingress
                  - ingress
                  - Route
                  - route
              ingress_annotations:
                description: Annotations to add to the ingress
                type: string
              ingress_tls_secret:
                description: Secret where the ingress TLS secret can be found
                type: string
              route_host:
                description: The DNS to use to points to the instance
                type: string
              route_tls_termination_mechanism:
                description: The secure TLS termination mechanism to use
                type: string
                default: Edge
                enum:
                  - Edge
                  - edge
                  - Passthrough
                  - passthrough
              route_tls_secret:
                description: Secret where the TLS related credentials are stored
                type: string
              redis_resource_requirements:
                description: Resource requirements for the Redis container
                properties:
                  requests:
                    properties:
                      cpu:
                        type: string
                      memory:
                        type: string
                      storage:
                        type: string
                    type: object
                  limits:
                    properties:
                      cpu:
                        type: string
                      memory:
                        type: string
                      storage:
                        type: string
                    type: object
                type: object
              pulp_web:
                description: The pulp web deployment.
                properties:
                  replicas:
                    description: The number of replicas for the deployment.
                    type: integer
                    default: 1
                    format: int32
                  resource_requirements:
                    description: Resource requirements for the pulp web container
                    properties:
                      requests:
                        properties:
                          cpu:
                            type: string
                          memory:
                            type: string
                          storage:
                            type: string
                        type: object
                      limits:
                        properties:
                          cpu:
                            type: string
                          memory:
                            type: string
                          storage:
                            type: string
                        type: object
                    type: object
                type: object
              pulp_api:
                description: The pulp api deployment.
                properties:
                  replicas:
                    description: The number of replicas for the deployment.
                    type: integer
                    default: 1
                    format: int32
                  log_level:
                    description: The log level for the deployment.
                    type: string
                    default: INFO
                    enum:
                      - DEBUG
                      - INFO
                      - WARNING
                      - ERROR
                      - CRITICAL
                  resource_requirements:
                    description: Resource requirements for the pulp api container
                    properties:
                      requests:
                        properties:
                          cpu:
                            type: string
                          memory:
                            type: string
                          storage:
                            type: string
                        type: object
                      limits:
                        properties:
                          cpu:
                            type: string
                          memory:
                            type: string
                          storage:
                            type: string
                        type: object
                    type: object
                type: object
              pulp_content:
                description: The pulp content deployment.
                properties:
                  replicas:
                    description: The number of replicas for the deployment.
                    type: integer
                    default: 2
                    format: int32
                  log_level:
                    description: The log level for the deployment.
                    type: string
                    default: INFO
                    enum:
                      - DEBUG
                      - INFO
                      - WARNING
                      - ERROR
                      - CRITICAL
                  resource_requirements:
                    description: Resource requirements for the pulp content container
                    properties:
                      requests:
                        properties:
                          cpu:
                            type: string
                          memory:
                            type: string
                          storage:
                            type: string
                        type: object
                      limits:
                        properties:
                          cpu:
                            type: string
                          memory:
                            type: string
                          storage:
                            type: string
                        type: object
                    type: object
                type: object
              pulp_worker:
                description: The pulp worker deployment.
                properties:
                  replicas:
                    description: The number of replicas for the deployment.
                    type: integer
                    default: 2
                    format: int32
                  resource_requirements:
                    description: Resource requirements for the pulp worker container
                    properties:
                      requests:
                        properties:
                          cpu:
                            type: string
                          memory:
                            type: string
                          storage:
                            type: string
                        type: object
                      limits:
                        properties:
                          cpu:
                            type: string
                          memory:
                            type: string
                          storage:
                            type: string
                        type: object
                    type: object
                type: object
              pulp_resource_manager:
                description: The pulp resource manager deployment.
                properties:
                  replicas:
                    description: The number of replicas for the deployment.
                    type: integer
                    default: 1
                    format: int32
                  resource_requirements:
                    description: Resource requirements for the pulp resource manager container
                    properties:
                      requests:
                        properties:
                          cpu:
                            type: string
                          memory:
                            type: string
                          storage:
                            type: string
                        type: object
                      limits:
                        properties:
                          cpu:
                            type: string
                          memory:
                            type: string
                          storage:
                            type: string
                        type: object
                    type: object
                type: object
            type: object
          status:
            properties:
              webURL:
                description: URL to access the deployed instance
                type: string
              adminPasswordSecret:
                description: Admin password of the deployed instance
                type: string
              deployedVersion:
                description: Version of the deployed instance
                type: string
              deployedImage:
                description: URL of the image used for the deployed instance
                type: string
              conditions:
                description: The resulting conditions when a Service Telemetry is instantiated
                items:
                  properties:
                    status:
                      type: string
                    type:
                      type: string
                    reason:
                      type: string
                    lastTransitionTime:
                      type: string
                  type: object
                type: array
            type: object
        type: object
        x-kubernetes-preserve-unknown-fields: true
