apiVersion: pulp.pulpproject.org/v1alpha1
kind: Pulp
metadata:
  name: example-pulp
spec:
  tag: "latest"
  pulp_file_storage:
    # k3s local-path requires this
    access_mode: "ReadWriteOnce"
    # We have a little over 10GB free on GHA VMs/instances
    size: "10Gi"
  database_connection:
    username: pulp
    password: pulp
    admin_password: pulp
