---
- set_fact:
    secret_key: "{{ lookup('password', '/dev/null length=50 chars=ascii_letters') }}"

- name: pulp-file-storage persistent volume claim
  k8s:
    apply: true
    definition: "{{ lookup('template', 'templates/' + item + '.pvc.yaml.j2') | from_yaml }}"
  with_items:
    - pulp-file-storage

# Workaround being unable to do the following, for the subsequent task:
# when: (pulp_settings is not defined) or
#   (pulp_settings.content_origin is not defined)
# (short-circuit evaluation only works for multiple separate when statements)
# https://github.com/ansible/ansible/issues/50554
- name: Setting CONTENT_ORIGIN
  set_fact:
    content_origin_temp: pulp_settings.content_origin
  when:
    - pulp_settings is defined
    - pulp_settings.content_origin is defined

- name: Getting raw pulp_settings
  set_fact:
    raw_pulp_settings: "{{ raw_spec['pulp_settings'] | default({}) }}"
  when: pulp_settings is defined

- include_tasks:
    file: get_node_ip.yml
  when: content_origin_temp is not defined

- name: Combining pulp_settings
  set_fact:
    pulp_combined_settings: "{{ pulp_default_settings|combine(raw_pulp_settings, recursive=True) if pulp_settings is defined and pulp_settings is not none else pulp_default_settings }}"

- name: pulp-server config-map
  k8s:
    apply: true
    definition: "{{ lookup('template', 'templates/' + item + '.config-map.yaml.j2') | from_yaml }}"
  with_items:
    - pulp-server

- name: pulp-api service
  k8s:
    apply: true
    definition: "{{ lookup('template', 'templates/' + item + '.service.yaml.j2') | from_yaml }}"
  with_items:
    - pulp-api

- name: pulp-api deployment
  k8s:
    apply: true
    definition: "{{ lookup('template', 'templates/' + item + '.deployment.yaml.j2') | from_yaml }}"
  with_items:
    - pulp-api
