---
# This is an example playbook to execute Ansible tests.
- name: Verify
  hosts: localhost
  connection: local
  gather_facts: no
  collections:
    - community.kubernetes

  vars:
    custom_resource: "{{ lookup('template', '/'.join([deploy_dir, 'crds/pulpproject_v1alpha1_pulp_cr.ci.yaml'])) | from_yaml }}"

  tasks:
    - name: Create the Pulp Custom Resource
      k8s:
        state: present
        namespace: '{{ namespace }}'
        definition: '{{ custom_resource }}'

    - name: Wait 15m for reconciliation to run
      k8s_info:
        api_version: '{{ custom_resource.apiVersion }}'
        kind: '{{ custom_resource.kind }}'
        namespace: '{{ namespace }}'
        name: '{{ custom_resource.metadata.name }}'
      register: cr
      until:
        - "'Successful' in (cr | json_query('resources[].status.conditions[].reason'))"
      delay: 6
      retries: 150

    - name: Get Pods
      k8s_info:
        api_version: v1
        kind: Pod
        namespace: '{{ namespace }}'
      register: pods

    - name: Output pods
      debug: var=pods

    - name: Example assertion
      assert:
        that: (pods | length) > 0
