---
- name: postgres persistent volume claim
  k8s:
    apply: true
    definition: "{{ lookup('template', 'templates/' + item + '.pvc.yaml.j2') | from_yaml }}"
  with_items:
    - postgres

- name: postgres service
  k8s:
    apply: true
    definition: "{{ lookup('template', 'templates/' + item + '.service.yaml.j2') | from_yaml }}"
  with_items:
    - postgres

- name: postgres deployment
  k8s:
    apply: true
    definition: "{{ lookup('template', 'templates/' + item + '.deployment.yaml.j2') | from_yaml }}"
  with_items:
    - postgres
